/*
 * cynsmsapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package apiclient_pkg

import "cynsmsapi_lib/configuration_pkg"

/*
 * Interface for the APICLIENT_IMPL
 */
type APICLIENT interface {
    CreateSendSMS (string, string, string, string) (string, error)

    GetBALANCECHECK (*GetBALANCECHECKInput, map[string]interface{}) (error)
}

/*
 * Factory for the APICLIENT interaface returning APICLIENT_IMPL
 */
func NewAPICLIENT(config configuration_pkg.CONFIGURATION) *APICLIENT_IMPL {
    client := new(APICLIENT_IMPL)
    client.config = config
    return client
}