/*
 * cynsmsapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package configuration_pkg


/** The base Uri for API calls */
const BASEURI string = "http://sms.cynojine.com/sms"



type CONFIGURATION_IMPL struct {
}

