/*
 * cynsmsapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package CynSMSAPIClient

import(
	"cynsmsapi_lib/configuration_pkg"
	"cynsmsapi_lib/api_pkg"
)
/*
 * Client structure as interface implementation
 */
type CYNSMSAPI_IMPL struct {
     api api_pkg.API
     config  configuration_pkg.CONFIGURATION
}

/**
     * Access to Configuration
     * @return Returns the Configuration instance
*/
func (me *CYNSMSAPI_IMPL) Configuration() configuration_pkg.CONFIGURATION {
    return me.config
}
/**
     * Access to API controller
     * @return Returns the API() instance
*/
func (me *CYNSMSAPI_IMPL) API() api_pkg.API {
    if(me.api) == nil {
        me.api = api_pkg.NewAPI(me.config)
    }
    return me.api
}

