/*
 * cynsmsapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package CynSMSAPIClient

import(
	"cynsmsapi_lib/configuration_pkg"
	"cynsmsapi_lib/api_pkg"
)


/*
 * Interface for the CYNSMSAPI_IMPL
 */
type CYNSMSAPI interface {
    API()                   api_pkg.API
    Configuration()         configuration_pkg.CONFIGURATION
}

/*
 * Factory for the CYNSMSAPI interface returning CYNSMSAPI_IMPL
 */
func NewCYNSMSAPI() CYNSMSAPI {
    cynSMSAPIClient := new(CYNSMSAPI_IMPL)
    cynSMSAPIClient.config = configuration_pkg.NewCONFIGURATION()

    return cynSMSAPIClient
}
